### ISSUE TITLE
请问下~

### ISSUE THREAD

**Issue by ylmyg** [Cuieney/vld#10]
请问下是否有非kotlin的版本呢？想学习非kotlin版本的源码

**Comment by Cuieney** [comment]
@ylmyg 有啊 其实这个就是从java 到kotlin 的 你可以下载下来看一下

**Comment by ylmyg** [comment]
你是说里面是java代码的么？主要是没有学习Kotlin，想先看java的
请问是从哪里下载java版本

**Comment by Cuieney** [comment]
你可以看一下项目的目录 在org.cuieney.videolife 包下有个kotlin 目录 里面是这个项目的kotlin代码，其他的包就是java代码了 在ui包下面可以找mainactivity.java




发自网易邮箱 iPhone 版
在2018年07月19日 16:13，ylmyg 写道：

你是说里面是java代码的么？主要是没有学习Kotlin，想先看java的
请问是从哪里下载java版本
