### ISSUE TITLE
DaggerAppComponent   为什么找不到这个类？？

### ISSUE THREAD

**Issue by zengjiaozi** [Cuieney/vld#2]

**Comment by Cuieney** [comment]
你是不是修改什么东西了

**Comment by Cuieney** [comment]
目前已改好，上次提交代码 改类名导致的，现在可以运行了 谢谢

**Comment by xuqinglong** [comment]
@Cuieney 还是DaggerAppComponent这个类找不到哦

**Comment by Cuieney** [comment]
你确定你没有修改代码？我这边删除本地，重新拉下来 安装时可以的

**Comment by xuqinglong** [comment]
@Cuieney 没有修改了，刚拉下来代码就报错了，嘿嘿

**Comment by xuqinglong** [comment]
在App.java中有用到import org.cuieney.videolife.di.component.DaggerAppComponent;可是org.cuieney.videolife.di.component包下就三个类，没有DaggerAppComponent

**Comment by Cuieney** [comment]
老铁们可以的，谢谢支持 你现在试试看看会不会出现这问题 @xuqinglong

**Comment by majiag** [comment]
这个是dragger自动生成的啊。老铁。

**Comment by Cuieney** [comment]
老铁棒棒的 @majiag
